brooklyn/brooklyn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
]

brooklyn/movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^pref/', views.pref, name='pref'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^rate/$', views.rate, name='rate'),
    url(r'^similar_movie/$', views.similar_movie, name='similar_movie'),
    url(r'^search/$', views.search, name='search'),
    url(r'^rated_movies/$', views.rated_movies, name='rated_movies'),
]

brooklyn/movies/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

# Create your models here.


class GenreSelect(models.Model):
    user = models.OneToOneField(User)
    Action = models.IntegerField(default=0)
    Adventure = models.IntegerField(default=0)
    Animation = models.IntegerField(default=0)
    Children = models.IntegerField(default=0)
    Comedy = models.IntegerField(default=0)
    Crime = models.IntegerField(default=0)
    Documentary = models.IntegerField(default=0)
    Drama = models.IntegerField(default=0)
    Fantasy = models.IntegerField(default=0)
    FilmNoir = models.IntegerField(default=0)
    Horror = models.IntegerField(default=0)
    Musical = models.IntegerField(default=0)
    Mystery = models.IntegerField(default=0)
    Romance = models.IntegerField(default=0)
    SciFi = models.IntegerField(default=0)
    Thriller = models.IntegerField(default=0)
    War = models.IntegerField(default=0)
    Western = models.IntegerField(default=0)


class UserRating(models.Model):
    class Meta:
        unique_together = (('user', 'movie_title'),)
    user = models.CharField(max_length=250)
    movie_title = models.CharField(max_length=250, default=0)
    rating = models.IntegerField(default=0)

    def __str__(self):  # __unicode__ on Python 2
        return str(self.rating)+self.movie_title


class Movies(models.Model):
    movieId = models.IntegerField(default=0)
    title = models.CharField(max_length=500)
    genres = models.CharField(max_length=500)

    def __str__(self):
        return str(self.title)

brooklyn/movies/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

brooklyn/movies/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic import View
from .forms import UserForm
from .models import GenreSelect, UserRating,Movies
from .rateform import RateForm
from .contentbased import contentbased
from .collabrative import collabrative
from .poster import imdb_id_from_title
from .poster import getposter
from .moviefetch import get_all_movies, getmovieid, getmovieposter
from .search import get_query
import itertools
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import operator
from .popular_movies import pop_mov
# Create your views here.


genrelist = {'genreaction': 'Action', 'genreadventure': 'Adventure',
             'genreanimation': 'Animation', 'genrechildren': 'Children',
             'genrecomedy': 'Comedy', 'genrecrime': 'Crime',
             'genredocumentary': 'Documentary', 'genredrama': 'Drama',
             'genrefantasy': 'Fantasy', 'genrefilmnoir': 'Filmnoir',
             'genrehorror': 'Horror', 'genremusical': 'Musical', 'genremystery': 'Mystery',
             'genreromance': 'Romance', 'genrescifi': 'Scifi', 'genrethriller': 'Thriller',
             'genrewar': 'War', 'genrewestern': 'Western'}


def index(request):
    template_name = 'movies/index.html'
    movie_title = []
    movie_overview = []
    movie_poster = []
    movie_rating = []
    movie_title, movie_overview, movie_poster, movie_rating = pop_mov()
    movie_detail = zip(movie_title, movie_overview, movie_poster, movie_rating)
    return render(request, template_name, {'genrelist': genrelist, 'movie_detail': movie_detail})


def pref(request):
    x = []
    prefe = get_object_or_404(GenreSelect)
    prefe.Action = request.POST.get('genreaction')
    x.append(prefe.Action)
    prefe.Adventure = request.POST.get('genreadventure')
    x.append(prefe.Adventure)
    prefe.Animation = request.POST.get('genreanimation')
    x.append(prefe.Animation)
    prefe.Children = request.POST.get('genrechildren')
    x.append(prefe.Children)
    prefe.Comedy = request.POST.get('genrecomedy')
    x.append(prefe.Comedy)
    prefe.Crime = request.POST.get('genrecrime')
    x.append(prefe.Crime)
    prefe.Documentary = request.POST.get('genredocumentary')
    x.append(prefe.Documentary)
    prefe.Drama = request.POST.get('genredrama')
    x.append(prefe.Drama)
    prefe.Fantasy = request.POST.get('genrefantasy')
    x.append(prefe.Fantasy)
    prefe.FilmNoir = request.POST.get('genrefilmnoir')
    x.append(prefe.FilmNoir)
    prefe.Horror = request.POST.get('genrehorror')
    x.append(prefe.Horror)
    prefe.Musical = request.POST.get('genremusical')
    x.append(prefe.Musical)
    prefe.Mystery = request.POST.get('genremystery')
    x.append(prefe.Mystery)
    prefe.Romance = request.POST.get('genreromance')
    x.append(prefe.Romance)
    prefe.SciFi = request.POST.get('genrescifi')
    x.append(prefe.SciFi)
    prefe.Thriller = request.POST.get('genrethriller')
    x.append(prefe.Thriller)
    prefe.War = request.POST.get('genrewar')
    x.append(prefe.War)
    prefe.Western = request.POST.get('genrewestern')
    x.append(prefe.Western)
    prefe.save()
    moviename=[]
    movieid=[]
    movieurl=[]
    y = contentbased(x)
    for j in y:
        moviename.append(j)
        movieid.append(imdb_id_from_title(j))
    #print(movieid)
    for i in movieid:
        if i is not None:
            movieurl.append(getposter(i))
        else:
            movieurl.append("D:/pilot_project/brooklyn/movies/static/movies/images/noimage.png")
    movienameurl = dict(zip(moviename, movieurl))




    return render(request, 'movies/contentbased.html', {'pref': prefe, 'genrelist': genrelist, 'movienameurl':movienameurl})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'movies/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #albums = Album.objects.filter(user=request.user)
                return render(request, 'movies/index.html')
            else:
                return render(request, 'movies/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'movies/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'movies/index.html')
    context = {
        "form": form,
    }
    return render(request, 'movies/register.html', context)


def rate(request):
    if request.method == 'POST':
        user = request.user
        movie_title = request.POST.get('movie_name')
        rating = request.POST.get('movie_rate')
        x=UserRating.objects.filter(user=user, movie_title= movie_title)
        if not x:
            print(x)
            rateobj = UserRating(user = user, movie_title = movie_title, rating = rating)
            rateobj.save()
        else:
            rateobj=UserRating.objects.get(user=user,movie_title=movie_title)
            rateobj.rating=rating
            rateobj.save()
    movie_list = []
    movie_list = get_all_movies()
    paginator = Paginator(movie_list, 3)
    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        movies = paginator.page(paginator.num_pages)
    movieid = getmovieid(movies)
    moviurl = getmovieposter(movieid)
    movienameurl = dict(zip(movies, moviurl))

    return render(request, 'movies/rate.html', {'movienameurl': movienameurl, 'movies': movies})


def similar_movie(request):
    user_movies = []
    movie_name = []
    movie_rating = []
    user_movies = list(UserRating.objects.filter(user=request.user))
    print(user_movies)
    for i in user_movies:
        x = str(i)
        movie_rating.append(int(x[0]))
        movie_name.append(x[1::])
    #print(movie_name[0])
    #print(movie_rating[0])
    user_movie_rate = dict(zip(movie_name, movie_rating))
    user_movies = sorted(user_movie_rate.items(), key=operator.itemgetter(1), reverse=True)
    movie_name = []
    for k, v in user_movies:
        movie_name.append(k)
        print(movie_name)
    recommend_movies = []
    recommend_movies = collabrative(movie_name)
    #print(recommend_movies)


    paginator = Paginator(recommend_movies, 3)
    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        movies = paginator.page(paginator.num_pages)
    movieid = getmovieid(movies)
    moviurl = getmovieposter(movieid)
    movienameurl = dict(zip(movies, moviurl))
    return render(request, 'movies/similar_moviepage.html', {'movienameurl': movienameurl, 'movies': movies})


def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = get_query(query_string, ['movieId', 'title','genres'])
        found_entries = Movies.objects.filter(entry_query)
    movies = []
    for temp in found_entries:
        movies.append(temp.title)
    movieid = getmovieid(movies)
    moviurl = getmovieposter(movieid)
    movienameurl = dict(zip(movies, moviurl))
    print(movies)
    return render(request, 'movies/search_results.html', {'query_string': query_string, 'found_entries': movienameurl})


def rated_movies(request):
    user = request.user
    user_movies = UserRating.objects.filter(user=user)
    movies = []
    movies_rate=[]
    if not user_movies:
        print("no movies")
    else:
        for temp in user_movies:
            movies.append(temp.movie_title)
            movies_rate.append(temp.rating)
        movieid = getmovieid(movies)
        moviurl = getmovieposter(movieid)
        movienameurl = zip(movies, moviurl,movies_rate)
        print(movies)
    return render(request,'movies/rated_movies.html', {'movienameurl': movienameurl})

brooklyn/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>brooklyn</title>
    {% load staticfiles %}
 <link rel="stylesheet" type="text/css" href="{% static 'movies/ratestylesheet.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
</head>
<body style="background-image: url('{% static "movies/images/background.jpg"%}')";>
<nav class="nav navbar-inverse">
    <div class="container-fluid">
        <!-- logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movies:index' %}">Brooklyn</a>

        </div>
        <!--item -->
        <div class="collapse navbar-collapse" id="topNavBar" >
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'movies:rated_movies' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Rated Movies
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'movies:rate' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Rate movies
                    </a>
                </li>

                 <li class="">
                    <a href="{% url 'movies:similar_movie' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Movies you may like
                    </a>
                </li>

            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'movies:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value=""/>
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">

                </li>
                {% if not user.is_authenticated %}
                <li class="">
                    <a href="{% url 'movies:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                        Login
                    </a>
                </li>
                {% else %}
                <li class="">
                <a href="{% url 'movies:logout_user' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
     </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

brooklyn/movies/templates/movies/contentbased.html
{% extends 'movies/base.html' %}

{% block body %}
<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});
</script>
<style>
#panel, #flip {
    padding: 5px;
    text-align: left;
    background-color: #e5eecc;
    border: solid 1px #c3c3c3;
}

#panel {
    padding: 50px;
    display: none;
}
</style>



<h1 style="color: white">Movies based on your preference</h1>

  <ul class="rig columns-3">
    {% for name,url in movienameurl.items %}
    <li><img src="{{ url }}" > <p>{{ name }}<p>
    </li>

    {% endfor %}
    </ul>
{% endblock %}

brooklyn/movies/templates/movies/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

brooklyn/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}
<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});
</script>
<style>
#panel, #flip {
    padding: 5px;
    text-align: left;
    background-color: #e5eecc;
    border: solid 1px #c3c3c3;
}

#panel {
    padding: 50px;
    display: none;
}
</style>



  <div id="flip">Add preference</div>
<div id="panel">
                <form class="form-horizontal" role="form" action="{% url 'movies:pref'%}" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                {% for x,y in genrelist.items %}
                <label style="margin-right: 40px">{{ y }}<select name={{ x }}>
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                    </label>
                {% endfor %}

                <input type="submit" value="submit"/>
                </form>

    </div>
  <h1 style="color: white">Popular movies</h1>

  <ul class="rig columns-3">
    {% for info in movie_detail %}
    <li><img src="{{ info.2 }}" align="left">
         <div align="right"><img src="http://pngimg.com/uploads/star/star_PNG1590.png" width="16" height="16" align="right"/><p>{{ info.3 }}</p></div>
    <h2 align="left" style="font-family: Sans-Serif">{{ info.0 }}</h2>
        <p align="middle">{{ info.1 }}</p>
    </li>

    {% endfor %}
    </ul>
{% endblock %}

brooklyn/movies/templates/movies/login.html
{% extends 'movies/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'movies:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'movies:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

brooklyn/movies/templates/movies/rate.html
{% extends 'movies/base.html' %}
{% block body %}
    <ul class="rig columns-3">
    {% for name,url in movienameurl.items %}
    <li><img src="{{ url }}" >
        <p>Rate</p>
         <form class="form-horizontal" role="form" action="{% url 'movies:rate'%}" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
             <input type="hidden" name="movie_name" value="{{ name }}">
                <select name="movie_rate"  >
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input type="submit" value="submit"/>
         </form>
   <!-- <span class="starRating">
        <input id="rating5" type="radio" name="rating" value="5">
        <label for="rating5">5</label>
        <input id="rating4" type="radio" name="rating" value="4">
        <label for="rating4">4</label>
        <input id="rating3" type="radio" name="rating" value="3">
        <label for="rating3">3</label>
        <input id="rating2" type="radio" name="rating" value="2">
        <label for="rating2">2</label>
        <input id="rating1" type="radio" name="rating" value="1">
        <label for="rating1">1</label>
      </span> -->




    </li>
    {% endfor %}
    </ul>
<div class="pagination">
    <span class="step-links">
        {% if movies.has_previous %}
            <a href="?page={{ movies.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
        </span>

        {% if movies.has_next %}
            <a href="?page={{ movies.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}
<script src="static/movies/js/main.js"></script>

brooklyn/movies/templates/movies/rated_movies.html
{% extends 'movies/base.html' %}
{% block body %}
     <ul class="rig columns-3">
    {% for info in movienameurl %}
    <li><img src="{{ info.1 }}" align="left">
         <div align="right"><img src="http://pngimg.com/uploads/star/star_PNG1590.png" width="16" height="16" align="right"/><h2>{{ info.2 }}</h2></div>
    <h2 align="left" style="font-family: Sans-Serif">{{ info.0 }}</h2>
    </li>

    {% endfor %}
    </ul>
{% endblock %}

brooklyn/movies/templates/movies/register.html
{% extends 'movies/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'movies:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

brooklyn/movies/templates/movies/search_results.html
{% extends 'movies/base.html' %}
{% block body %}
    <h1 style="color: white">Search results</h1>
    <ul class="rig columns-3">
    {% for movie_name,url in found_entries.items %}
        <li><img src="{{ url }}">
            {{movie_name}}
         <form class="form-horizontal" role="form" action="{% url 'movies:rate'%}" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
             <input type="hidden" name="movie_name" value="{{ movie_name }}">
                <select name="movie_rate"  >
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input type="submit" value="submit"/>
         </form>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

brooklyn/movies/templates/movies/similar_moviepage.html
{% extends 'movies/base.html' %}
{% block body %}
     <ul class="rig columns-3">
    {% for name,url in movienameurl.items %}
    <li><img src="{{ url }}" ><h2>{{ name }}</h2>
      </li>
    {% endfor %}
    </ul>
<div class="pagination">
    <span class="step-links">
        {% if movies.has_previous %}
            <a href="?page={{ movies.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
        </span>

        {% if movies.has_next %}
            <a href="?page={{ movies.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}